# Generated by Django 5.2.12 on 2026-03-13 13:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEstablishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='api.governorate')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.schoolestablishment')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_used', models.CharField(choices=[('FR', 'French'), ('AR', 'Arabic')], default='FR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tobacco_user', models.BooleanField(default=False)),
                ('ecig_user', models.BooleanField(default=False)),
                ('hookah_user', models.BooleanField(default=False)),
                ('alcohol_user', models.BooleanField(default=False)),
                ('tranquilizer_user', models.BooleanField(default=False)),
                ('cannabis_user', models.BooleanField(default=False)),
                ('cocaine_user', models.BooleanField(default=False)),
                ('ecstasy_user', models.BooleanField(default=False)),
                ('heroin_user', models.BooleanField(default=False)),
                ('inhalant_user', models.BooleanField(default=False)),
                ('has_risk_behavior', models.BooleanField(default=False)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.governorate')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.schoolclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.schoolestablishment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('USER', 'User (Doctor)'), ('ADMIN', 'Admin (Governorate)'), ('SUPERADMIN', 'Super Admin (National)')], default='USER', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.governorate')),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.schoolestablishment')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SectionA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('birth_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activities_frequency', models.JSONField(blank=True, default=dict)),
                ('school_absences', models.JSONField(blank=True, default=dict)),
                ('academic_performance', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Bien'), ('average', 'Moyen'), ('below_average', 'Faible'), ('failing', 'Tres faible')], max_length=20)),
                ('lives_with_father', models.BooleanField(blank=True, null=True)),
                ('lives_with_mother', models.BooleanField(blank=True, null=True)),
                ('lives_with_siblings', models.BooleanField(blank=True, null=True)),
                ('lives_with_grandparents', models.BooleanField(blank=True, null=True)),
                ('lives_with_other', models.BooleanField(blank=True, null=True)),
                ('parents_absence_reason', models.CharField(blank=True, choices=[('death', 'Deces'), ('divorce', 'Divorce'), ('migration', 'Migration'), ('other', 'Autre')], max_length=20)),
                ('nights_out_30days', models.CharField(blank=True, choices=[('0', '0'), ('1_2', '1-2'), ('3_5', '3-5'), ('6_9', '6-9'), ('10_plus', '10+')], max_length=10)),
                ('family_relationship_satisfaction', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_a', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_education', models.CharField(blank=True, choices=[('none', 'Sans instruction'), ('primary', 'Primaire'), ('secondary', 'Secondaire'), ('higher', 'Superieur'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('mother_education', models.CharField(blank=True, choices=[('none', 'Sans instruction'), ('primary', 'Primaire'), ('secondary', 'Secondaire'), ('higher', 'Superieur'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('father_employed', models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10)),
                ('mother_employed', models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10)),
                ('family_economic_status', models.CharField(blank=True, choices=[('much_above', 'Bien au-dessus'), ('above', 'Au-dessus'), ('average', 'Dans la moyenne'), ('below', 'En-dessous'), ('much_below', 'Bien en-dessous'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_b', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_difficulty', models.CharField(blank=True, choices=[('very_easy', 'Tres facile'), ('easy', 'Facile'), ('difficult', 'Difficile'), ('very_difficult', 'Tres difficile'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('family_friends_smoke', models.JSONField(blank=True, default=dict)),
                ('lifetime_frequency', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20)),
                ('frequency_30days', models.CharField(blank=True, choices=[('never', 'Jamais'), ('lt1_week', "Moins d'une fois par semaine"), ('lt1_day', "Moins d'une fois par jour"), ('1_5_day', '1-5 par jour'), ('6_10_day', '6-10 par jour'), ('11_20_day', '11-20 par jour'), ('gt20_day', 'Plus de 20 par jour')], max_length=20)),
                ('age_first_cigarette', models.CharField(blank=True, choices=[('never', 'Jamais'), ('7_or_less', '7 ans ou moins'), ('8', '8 ans'), ('9', '9 ans'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('16', '16 ans'), ('17', '17 ans'), ('18_plus', '18 ans ou plus')], max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_c', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_difficulty', models.CharField(blank=True, choices=[('very_easy', 'Tres facile'), ('easy', 'Facile'), ('difficult', 'Difficile'), ('very_difficult', 'Tres difficile'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('family_friends_vape', models.JSONField(blank=True, default=dict)),
                ('lifetime_frequency', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20)),
                ('frequency_30days', models.CharField(blank=True, choices=[('never', 'Jamais'), ('lt1_week', "Moins d'une fois par semaine"), ('lt1_day', "Moins d'une fois par jour"), ('1_5_day', '1-5 par jour'), ('6_10_day', '6-10 par jour'), ('11_20_day', '11-20 par jour'), ('gt20_day', 'Plus de 20 par jour')], max_length=20)),
                ('age_first_use', models.CharField(blank=True, choices=[('never', 'Jamais'), ('7_or_less', '7 ans ou moins'), ('8', '8 ans'), ('9', '9 ans'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('16', '16 ans'), ('17', '17 ans'), ('18_plus', '18 ans ou plus')], max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_d', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_difficulty', models.CharField(blank=True, choices=[('very_easy', 'Tres facile'), ('easy', 'Facile'), ('difficult', 'Difficile'), ('very_difficult', 'Tres difficile'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('family_friends_hookah', models.JSONField(blank=True, default=dict)),
                ('lifetime_frequency', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20)),
                ('frequency_30days', models.CharField(blank=True, choices=[('never', 'Jamais'), ('lt1_week', "Moins d'une fois par semaine"), ('lt1_day', "Moins d'une fois par jour"), ('1_5_day', '1-5 par jour'), ('6_10_day', '6-10 par jour'), ('11_20_day', '11-20 par jour'), ('gt20_day', 'Plus de 20 par jour')], max_length=20)),
                ('age_first_use', models.CharField(blank=True, choices=[('never', 'Jamais'), ('7_or_less', '7 ans ou moins'), ('8', '8 ans'), ('9', '9 ans'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('16', '16 ans'), ('17', '17 ans'), ('18_plus', '18 ans ou plus')], max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_e', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_difficulty', models.JSONField(blank=True, default=dict)),
                ('family_friends_drink', models.JSONField(blank=True, default=dict)),
                ('lifetime_frequency', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20)),
                ('frequency_30days_by_type', models.JSONField(blank=True, default=dict)),
                ('binge_drinking_30days', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_plus', '20 fois ou plus')], max_length=20)),
                ('intoxication_frequency', models.JSONField(blank=True, default=dict)),
                ('age_first_drink', models.CharField(blank=True, choices=[('never', 'Jamais'), ('7_or_less', '7 ans ou moins'), ('8', '8 ans'), ('9', '9 ans'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('16', '16 ans'), ('17', '17 ans'), ('18_plus', '18 ans ou plus')], max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_g', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_difficulty', models.CharField(blank=True, choices=[('very_easy', 'Tres facile'), ('easy', 'Facile'), ('difficult', 'Difficile'), ('very_difficult', 'Tres difficile'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('family_friends_use', models.JSONField(blank=True, default=dict)),
                ('lifetime_frequency', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20)),
                ('age_first_use', models.CharField(blank=True, choices=[('never', 'Jamais'), ('7_or_less', '7 ans ou moins'), ('8', '8 ans'), ('9', '9 ans'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('16', '16 ans'), ('17', '17 ans'), ('18_plus', '18 ans ou plus')], max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_h', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_difficulty', models.CharField(blank=True, choices=[('very_easy', 'Tres facile'), ('easy', 'Facile'), ('difficult', 'Difficile'), ('very_difficult', 'Tres difficile'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('family_friends_use', models.JSONField(blank=True, default=dict)),
                ('lifetime_frequency', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20)),
                ('age_first_use', models.CharField(blank=True, choices=[('never', 'Jamais'), ('7_or_less', '7 ans ou moins'), ('8', '8 ans'), ('9', '9 ans'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('16', '16 ans'), ('17', '17 ans'), ('18_plus', '18 ans ou plus')], max_length=10)),
                ('types_used_12months', models.JSONField(blank=True, default=dict)),
                ('used_last_12months', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_plus', '20 fois ou plus')], max_length=20)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_i', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_difficulty', models.CharField(blank=True, choices=[('very_easy', 'Tres facile'), ('easy', 'Facile'), ('difficult', 'Difficile'), ('very_difficult', 'Tres difficile'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('family_friends_use', models.JSONField(blank=True, default=dict)),
                ('lifetime_frequency', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20)),
                ('age_first_use', models.CharField(blank=True, choices=[('never', 'Jamais'), ('7_or_less', '7 ans ou moins'), ('8', '8 ans'), ('9', '9 ans'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('16', '16 ans'), ('17', '17 ans'), ('18_plus', '18 ans ou plus')], max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_j', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_difficulty', models.CharField(blank=True, choices=[('very_easy', 'Tres facile'), ('easy', 'Facile'), ('difficult', 'Difficile'), ('very_difficult', 'Tres difficile'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('family_friends_use', models.JSONField(blank=True, default=dict)),
                ('lifetime_frequency', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20)),
                ('age_first_use', models.CharField(blank=True, choices=[('never', 'Jamais'), ('7_or_less', '7 ans ou moins'), ('8', '8 ans'), ('9', '9 ans'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('16', '16 ans'), ('17', '17 ans'), ('18_plus', '18 ans ou plus')], max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_k', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_difficulty', models.CharField(blank=True, choices=[('very_easy', 'Tres facile'), ('easy', 'Facile'), ('difficult', 'Difficile'), ('very_difficult', 'Tres difficile'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('family_friends_use', models.JSONField(blank=True, default=dict)),
                ('lifetime_frequency', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20)),
                ('age_first_use', models.CharField(blank=True, choices=[('never', 'Jamais'), ('7_or_less', '7 ans ou moins'), ('8', '8 ans'), ('9', '9 ans'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('16', '16 ans'), ('17', '17 ans'), ('18_plus', '18 ans ou plus')], max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_l', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_difficulty', models.CharField(blank=True, choices=[('very_easy', 'Tres facile'), ('easy', 'Facile'), ('difficult', 'Difficile'), ('very_difficult', 'Tres difficile'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('family_friends_use', models.JSONField(blank=True, default=dict)),
                ('lifetime_frequency', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20)),
                ('age_first_use', models.CharField(blank=True, choices=[('never', 'Jamais'), ('7_or_less', '7 ans ou moins'), ('8', '8 ans'), ('9', '9 ans'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('16', '16 ans'), ('17', '17 ans'), ('18_plus', '18 ans ou plus')], max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_m', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_difficulty', models.JSONField(blank=True, default=dict)),
                ('lifetime_frequency', models.JSONField(blank=True, default=dict)),
                ('frequency_12months', models.JSONField(blank=True, default=dict)),
                ('age_first_use', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_n', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substances_frequency', models.JSONField(blank=True, default=dict)),
                ('new_substance_forms', models.JSONField(blank=True, default=dict)),
                ('lifetime_substance_frequency', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_p', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_perception_tobacco', models.JSONField(blank=True, default=dict)),
                ('risk_perception_alcohol', models.JSONField(blank=True, default=dict)),
                ('knows_where_to_get_help', models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_q', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.CharField(blank=True, choices=[('0', '0h'), ('lt1h', '<1h'), ('1_3h', '1-3h'), ('4_6h', '4-6h'), ('7_9h', '7-9h'), ('10_plus', '10h+')], max_length=20)),
                ('social_media_statements', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_r', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_month', models.CharField(blank=True, choices=[('0', '0h'), ('lt1h', '<1h'), ('1_3h', '1-3h'), ('4_6h', '4-6h'), ('7_9h', '7-9h'), ('10_plus', '10h+')], max_length=20)),
                ('days_per_week', models.CharField(blank=True, max_length=10)),
                ('gaming_statements', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_s', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambling_frequency_12months', models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_plus', '20 fois ou plus')], max_length=20)),
                ('offline_game_types', models.JSONField(blank=True, default=dict)),
                ('online_game_types', models.JSONField(blank=True, default=dict)),
                ('felt_need_to_increase_bets', models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10)),
                ('lied_about_betting', models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10)),
                ('gambling_related_issues', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_t', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fights_12months', models.CharField(blank=True, choices=[('0', '0 fois'), ('1', '1 fois'), ('2_3', '2-3 fois'), ('4_5', '4-5 fois'), ('6_7', '6-7 fois'), ('8_9', '8-9 fois'), ('10_11', '10-11 fois'), ('12_plus', '12 fois ou plus')], max_length=10)),
                ('last_fight_circumstance', models.CharField(blank=True, choices=[('initiated', "J'etais l'initiateur"), ('attacked', "J'ai ete attaque")], max_length=20)),
                ('fight_location', models.CharField(blank=True, choices=[('school', 'Au sein du lycee'), ('outside', "A l'exterieur du lycee")], max_length=20)),
                ('school_staff_intervene', models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10)),
                ('fight_consequences', models.JSONField(blank=True, default=dict)),
                ('serious_injury_12months', models.CharField(blank=True, choices=[('none', 'Pas de blessure grave'), ('self_accidental', 'Blessure accidentelle (moi-meme)'), ('other_accidental', "Blesse accidentellement par quelqu'un d'autre"), ('self_deliberate', 'Blessure deliberee (moi-meme)'), ('other_deliberate', "Blesse deliberement par quelqu'un d'autre")], max_length=25)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_u', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_control_life', models.CharField(blank=True, choices=[('never', 'Jamais'), ('almost_never', 'Presque jamais'), ('sometimes', 'Parfois'), ('fairly_often', 'Assez souvent'), ('very_often', 'Tres souvent')], max_length=20)),
                ('confident_handling_problems', models.CharField(blank=True, choices=[('never', 'Jamais'), ('almost_never', 'Presque jamais'), ('sometimes', 'Parfois'), ('fairly_often', 'Assez souvent'), ('very_often', 'Tres souvent')], max_length=20)),
                ('things_going_my_way', models.CharField(blank=True, choices=[('never', 'Jamais'), ('almost_never', 'Presque jamais'), ('sometimes', 'Parfois'), ('fairly_often', 'Assez souvent'), ('very_often', 'Tres souvent')], max_length=20)),
                ('difficulties_piling_up', models.CharField(blank=True, choices=[('never', 'Jamais'), ('almost_never', 'Presque jamais'), ('sometimes', 'Parfois'), ('fairly_often', 'Assez souvent'), ('very_often', 'Tres souvent')], max_length=20)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_v', to='api.questionnairesession')),
            ],
        ),
        migrations.CreateModel(
            name='SectionZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honesty_check_alcohol', models.CharField(blank=True, choices=[('yes_same', 'Oui, de la meme facon'), ('no_different', 'Non, differemment'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('honesty_check_cannabis', models.CharField(blank=True, choices=[('yes_same', 'Oui, de la meme facon'), ('no_different', 'Non, differemment'), ('dont_know', 'Je ne sais pas')], max_length=20)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_z', to='api.questionnairesession')),
            ],
        ),
    ]
