# Generated by Django 5.2.12 on 2026-03-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectiong',
            old_name='family_friends_drink',
            new_name='days_30_by_type',
        ),
        migrations.RenameField(
            model_name='sectioni',
            old_name='family_friends_use',
            new_name='cannabis_problems_12months',
        ),
        migrations.RenameField(
            model_name='sectioni',
            old_name='types_used_12months',
            new_name='cannabis_types_12months',
        ),
        migrations.RenameField(
            model_name='sectionn',
            old_name='access_difficulty',
            new_name='access_grid',
        ),
        migrations.RenameField(
            model_name='sectionn',
            old_name='age_first_use',
            new_name='age_first_grid',
        ),
        migrations.RenameField(
            model_name='sectionn',
            old_name='frequency_12months',
            new_name='lifetime_grid',
        ),
        migrations.RenameField(
            model_name='sectionn',
            old_name='lifetime_frequency',
            new_name='months_12_grid',
        ),
        migrations.RenameField(
            model_name='sectionq',
            old_name='risk_perception_alcohol',
            new_name='risk_perception',
        ),
        migrations.RenameField(
            model_name='sectiont',
            old_name='gambling_related_issues',
            new_name='gambling_behavior',
        ),
        migrations.RenameField(
            model_name='sectiont',
            old_name='offline_game_types',
            new_name='offline_freq_grid',
        ),
        migrations.RenameField(
            model_name='sectiont',
            old_name='online_game_types',
            new_name='online_freq_grid',
        ),
        migrations.RemoveField(
            model_name='sectiona',
            name='lives_with_father',
        ),
        migrations.RemoveField(
            model_name='sectiona',
            name='lives_with_grandparents',
        ),
        migrations.RemoveField(
            model_name='sectiona',
            name='lives_with_mother',
        ),
        migrations.RemoveField(
            model_name='sectiona',
            name='lives_with_other',
        ),
        migrations.RemoveField(
            model_name='sectiona',
            name='lives_with_siblings',
        ),
        migrations.RemoveField(
            model_name='sectionb',
            name='family_economic_status',
        ),
        migrations.RemoveField(
            model_name='sectionb',
            name='father_employed',
        ),
        migrations.RemoveField(
            model_name='sectionb',
            name='mother_employed',
        ),
        migrations.RemoveField(
            model_name='sectionc',
            name='age_first_cigarette',
        ),
        migrations.RemoveField(
            model_name='sectionc',
            name='family_friends_smoke',
        ),
        migrations.RemoveField(
            model_name='sectionc',
            name='frequency_30days',
        ),
        migrations.RemoveField(
            model_name='sectionc',
            name='lifetime_frequency',
        ),
        migrations.RemoveField(
            model_name='sectiond',
            name='family_friends_vape',
        ),
        migrations.RemoveField(
            model_name='sectiond',
            name='frequency_30days',
        ),
        migrations.RemoveField(
            model_name='sectiond',
            name='lifetime_frequency',
        ),
        migrations.RemoveField(
            model_name='sectione',
            name='family_friends_hookah',
        ),
        migrations.RemoveField(
            model_name='sectione',
            name='frequency_30days',
        ),
        migrations.RemoveField(
            model_name='sectione',
            name='lifetime_frequency',
        ),
        migrations.RemoveField(
            model_name='sectiong',
            name='frequency_30days_by_type',
        ),
        migrations.RemoveField(
            model_name='sectiong',
            name='intoxication_frequency',
        ),
        migrations.RemoveField(
            model_name='sectiong',
            name='lifetime_frequency',
        ),
        migrations.RemoveField(
            model_name='sectionh',
            name='family_friends_use',
        ),
        migrations.RemoveField(
            model_name='sectionh',
            name='lifetime_frequency',
        ),
        migrations.RemoveField(
            model_name='sectioni',
            name='lifetime_frequency',
        ),
        migrations.RemoveField(
            model_name='sectioni',
            name='used_last_12months',
        ),
        migrations.RemoveField(
            model_name='sectionj',
            name='family_friends_use',
        ),
        migrations.RemoveField(
            model_name='sectionj',
            name='lifetime_frequency',
        ),
        migrations.RemoveField(
            model_name='sectionk',
            name='family_friends_use',
        ),
        migrations.RemoveField(
            model_name='sectionk',
            name='lifetime_frequency',
        ),
        migrations.RemoveField(
            model_name='sectionl',
            name='family_friends_use',
        ),
        migrations.RemoveField(
            model_name='sectionl',
            name='lifetime_frequency',
        ),
        migrations.RemoveField(
            model_name='sectionm',
            name='family_friends_use',
        ),
        migrations.RemoveField(
            model_name='sectionm',
            name='lifetime_frequency',
        ),
        migrations.RemoveField(
            model_name='sectionq',
            name='risk_perception_tobacco',
        ),
        migrations.RemoveField(
            model_name='sectionr',
            name='hours_per_week',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='hours_per_month',
        ),
        migrations.RemoveField(
            model_name='sectiont',
            name='felt_need_to_increase_bets',
        ),
        migrations.RemoveField(
            model_name='sectiont',
            name='gambling_frequency_12months',
        ),
        migrations.RemoveField(
            model_name='sectiont',
            name='lied_about_betting',
        ),
        migrations.RemoveField(
            model_name='sectionz',
            name='honesty_check_alcohol',
        ),
        migrations.RemoveField(
            model_name='sectionz',
            name='honesty_check_cannabis',
        ),
        migrations.AddField(
            model_name='sectiona',
            name='household_members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='economic_status',
            field=models.CharField(blank=True, choices=[('superior', 'Supérieure aux autres familles'), ('identical', 'Identique aux autres familles'), ('inferior', 'Inférieure aux autres familles')], max_length=20),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='father_job',
            field=models.CharField(blank=True, choices=[('full_time', 'Oui, à plein temps'), ('part_time', 'Oui, temps partiel'), ('unemployed', 'Ne travaille pas'), ('retired', 'Retraité(e)'), ('dont_know', 'Je ne sais pas'), ('na', 'Non applicable')], max_length=20),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='mother_job',
            field=models.CharField(blank=True, choices=[('full_time', 'Oui, à plein temps'), ('part_time', 'Oui, temps partiel'), ('unemployed', 'Ne travaille pas'), ('retired', 'Retraité(e)'), ('dont_know', 'Je ne sais pas'), ('na', 'Non applicable')], max_length=20),
        ),
        migrations.AddField(
            model_name='sectionc',
            name='age_daily_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionc',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionc',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('lt1_week', '< 1 cigarette par semaine'), ('lt1_day', '< 1 cigarette par jour'), ('1_5_day', '1-5 par jour'), ('6_10_day', '6-10 par jour'), ('11_20_day', '11-20 par jour'), ('gt20_day', '> 20 par jour')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionc',
            name='family_smoke',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionc',
            name='friends_smoke',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionc',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionc',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiond',
            name='age_daily_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiond',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('lt1_week', '< 1 fois par semaine'), ('ge1_week', 'Au moins 1 fois par semaine'), ('daily', 'Tous les jours ou presque')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectiond',
            name='family_vape',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiond',
            name='friends_vape',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiond',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiond',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectione',
            name='age_daily_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectione',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('lt1_week', '< 1 par semaine'), ('lt1_day', '< 1 par jour'), ('1_5_day', '1-5 par jour'), ('6_10_day', '6-10 par jour'), ('11_20_day', '11-20 par jour'), ('gt20_day', '> 20 par jour')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectione',
            name='family_hookah',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectione',
            name='friends_hookah',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectione',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectione',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiong',
            name='age_first_intoxication',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiong',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiong',
            name='family_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiong',
            name='friends_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiong',
            name='intoxication_12months',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiong',
            name='intoxication_30days',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiong',
            name='intoxication_lifetime',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiong',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiong',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionh',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionh',
            name='family_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionh',
            name='friends_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionh',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionh',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectioni',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectioni',
            name='family_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectioni',
            name='friends_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectioni',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectioni',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionj',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionj',
            name='family_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionj',
            name='friends_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionj',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionj',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionk',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionk',
            name='family_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionk',
            name='friends_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionk',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionk',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionl',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionl',
            name='family_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionl',
            name='friends_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionl',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionl',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionm',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionm',
            name='family_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionm',
            name='friends_use',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Ne sait pas')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionm',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionm',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionr',
            name='days_per_week',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sectionr',
            name='duration_non_school_day',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('30m', 'Une demi-heure ou moins'), ('1h', 'Environ 1 heure'), ('2_3h', 'Environ 2-3 heures'), ('4_5h', 'Environ 4-5 heures'), ('6h_plus', '6 heures ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionr',
            name='duration_school_day',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('30m', 'Une demi-heure ou moins'), ('1h', 'Environ 1 heure'), ('2_3h', 'Environ 2-3 heures'), ('4_5h', 'Environ 4-5 heures'), ('6h_plus', '6 heures ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sections',
            name='duration_non_school_day',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('30m', 'Une demi-heure ou moins'), ('1h', 'Environ 1 heure'), ('2_3h', 'Environ 2-3 heures'), ('4_5h', 'Environ 4-5 heures'), ('6h_plus', '6 heures ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sections',
            name='duration_school_day',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('30m', 'Une demi-heure ou moins'), ('1h', 'Environ 1 heure'), ('2_3h', 'Environ 2-3 heures'), ('4_5h', 'Environ 4-5 heures'), ('6h_plus', '6 heures ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiont',
            name='frequency_12months',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionz',
            name='honesty_alcohol',
            field=models.CharField(blank=True, choices=[('admitted', 'J’ai déjà déclaré [cela]'), ('yes_undoubtedly', 'Oui, sans aucun doute'), ('probably_yes', 'Probablement oui'), ('probably_no', 'Probablement pas'), ('no_undoubtedly', 'Non, sans aucun doute')], max_length=20),
        ),
        migrations.AddField(
            model_name='sectionz',
            name='honesty_cannabis',
            field=models.CharField(blank=True, choices=[('admitted', 'J’ai déjà déclaré [cela]'), ('yes_undoubtedly', 'Oui, sans aucun doute'), ('probably_yes', 'Probablement oui'), ('probably_no', 'Probablement pas'), ('no_undoubtedly', 'Non, sans aucun doute')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='academic_performance',
            field=models.CharField(blank=True, choices=[('below_10', 'En dessous de la moyenne (<10/20)'), ('10_12', 'Moyen [10 – 12]'), ('above_12', 'En dessus de la moyenne (>12/20)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='nights_out_30days',
            field=models.CharField(blank=True, choices=[('0', 'Aucune'), ('1', '1 nuit'), ('2', '2 nuits'), ('3', '3 nuits'), ('4', '4 nuits'), ('5', '5 nuits'), ('6', '6 nuits'), ('7_plus', '7 nuits ou plus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='parents_absence_reason',
            field=models.CharField(blank=True, choices=[('death', 'Décès'), ('divorce', 'Divorce'), ('migration', 'Migration'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='father_education',
            field=models.CharField(blank=True, choices=[('none', 'Non scolarisé'), ('primary_no_6th', 'Primaire (échec 6ème)'), ('primary_6th', 'Primaire (réussi 6ème)'), ('college_no_9th', 'Collège (échec 9ème)'), ('college_9th', 'Collège (réussi 9ème)'), ('secondary_no_bac', 'Secondaire (échec bac)'), ('secondary_bac', 'Secondaire (réussi bac)'), ('university', 'Universitaire ou plus'), ('vocational', 'Formation professionnelle'), ('dont_know', 'Ne sait pas'), ('na', 'Non applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='mother_education',
            field=models.CharField(blank=True, choices=[('none', 'Non scolarisé'), ('primary_no_6th', 'Primaire (échec 6ème)'), ('primary_6th', 'Primaire (réussi 6ème)'), ('college_no_9th', 'Collège (échec 9ème)'), ('college_9th', 'Collège (réussi 9ème)'), ('secondary_no_bac', 'Secondaire (échec bac)'), ('secondary_bac', 'Secondaire (réussi bac)'), ('university', 'Universitaire ou plus'), ('vocational', 'Formation professionnelle'), ('dont_know', 'Ne sait pas'), ('na', 'Non applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionc',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('impossible', 'Impossible'), ('difficult', 'Difficile'), ('easy', 'Facile'), ('dont_know', 'Ne sait pas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('impossible', 'Impossible'), ('difficult', 'Difficile'), ('easy', 'Facile'), ('dont_know', 'Ne sait pas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectione',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('impossible', 'Impossible'), ('difficult', 'Difficile'), ('easy', 'Facile'), ('dont_know', 'Ne sait pas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectione',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='age_first_drink',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='binge_drinking_30days',
            field=models.CharField(blank=True, choices=[('0', 'Aucune fois'), ('1', '1'), ('2', '2'), ('3_5', '3-5'), ('6_9', '6-9'), ('10_plus', '≥ 10')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionh',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('impossible', 'Impossible'), ('difficult', 'Difficile'), ('easy', 'Facile'), ('dont_know', 'Ne sait pas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sectionh',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectioni',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('impossible', 'Impossible'), ('difficult', 'Difficile'), ('easy', 'Facile'), ('dont_know', 'Ne sait pas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sectioni',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionj',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('impossible', 'Impossible'), ('difficult', 'Difficile'), ('easy', 'Facile'), ('dont_know', 'Ne sait pas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sectionj',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionk',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('impossible', 'Impossible'), ('difficult', 'Difficile'), ('easy', 'Facile'), ('dont_know', 'Ne sait pas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sectionk',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionl',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('impossible', 'Impossible'), ('difficult', 'Difficile'), ('easy', 'Facile'), ('dont_know', 'Ne sait pas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sectionl',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionm',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('impossible', 'Impossible'), ('difficult', 'Difficile'), ('easy', 'Facile'), ('dont_know', 'Ne sait pas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sectionm',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionv',
            name='cant_control_life',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('almost_never', 'Presque jamais'), ('sometimes', 'Parfois'), ('fairly_often', 'Assez souvent'), ('very_often', 'Très souvent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionv',
            name='confident_handling_problems',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('almost_never', 'Presque jamais'), ('sometimes', 'Parfois'), ('fairly_often', 'Assez souvent'), ('very_often', 'Très souvent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionv',
            name='difficulties_piling_up',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('almost_never', 'Presque jamais'), ('sometimes', 'Parfois'), ('fairly_often', 'Assez souvent'), ('very_often', 'Très souvent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionv',
            name='things_going_my_way',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('almost_never', 'Presque jamais'), ('sometimes', 'Parfois'), ('fairly_often', 'Assez souvent'), ('very_often', 'Très souvent')], max_length=20),
        ),
    ]
