# Generated by Django 5.2.12 on 2026-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_family_friends_drink_sectiong_days_30_by_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionu',
            old_name='school_staff_intervene',
            new_name='bullied',
        ),
        migrations.RenameField(
            model_name='sectionv',
            old_name='cant_control_life',
            new_name='depressed',
        ),
        migrations.RenameField(
            model_name='sectionv',
            old_name='confident_handling_problems',
            new_name='effort',
        ),
        migrations.RenameField(
            model_name='sectionv',
            old_name='difficulties_piling_up',
            new_name='hopeless',
        ),
        migrations.RenameField(
            model_name='sectionv',
            old_name='things_going_my_way',
            new_name='nervous',
        ),
        migrations.RemoveField(
            model_name='sectionn',
            name='access_grid',
        ),
        migrations.RemoveField(
            model_name='sectionn',
            name='age_first_grid',
        ),
        migrations.RemoveField(
            model_name='sectionn',
            name='lifetime_grid',
        ),
        migrations.RemoveField(
            model_name='sectionn',
            name='months_12_grid',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='lifetime_substance_frequency',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='new_substance_forms',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='substances_frequency',
        ),
        migrations.RemoveField(
            model_name='sectionq',
            name='knows_where_to_get_help',
        ),
        migrations.RemoveField(
            model_name='sectionq',
            name='risk_perception',
        ),
        migrations.RemoveField(
            model_name='sectionr',
            name='duration_non_school_day',
        ),
        migrations.RemoveField(
            model_name='sectionr',
            name='duration_school_day',
        ),
        migrations.RemoveField(
            model_name='sectionr',
            name='social_media_statements',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='duration_non_school_day',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='duration_school_day',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='gaming_statements',
        ),
        migrations.RemoveField(
            model_name='sectiont',
            name='frequency_12months',
        ),
        migrations.RemoveField(
            model_name='sectiont',
            name='gambling_behavior',
        ),
        migrations.RemoveField(
            model_name='sectiont',
            name='offline_freq_grid',
        ),
        migrations.RemoveField(
            model_name='sectiont',
            name='online_freq_grid',
        ),
        migrations.RemoveField(
            model_name='sectionu',
            name='fight_consequences',
        ),
        migrations.RemoveField(
            model_name='sectionu',
            name='fight_location',
        ),
        migrations.RemoveField(
            model_name='sectionu',
            name='last_fight_circumstance',
        ),
        migrations.RemoveField(
            model_name='sectionz',
            name='honesty_alcohol',
        ),
        migrations.RemoveField(
            model_name='sectionz',
            name='honesty_cannabis',
        ),
        migrations.AddField(
            model_name='sectionn',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionq',
            name='friend_use_risk',
            field=models.CharField(blank=True, choices=[('definitely_no', 'Pas du tout'), ('probably_no', 'Probable non'), ('probably_yes', 'Probable oui'), ('definitely_yes', 'Certainement')], max_length=20),
        ),
        migrations.AddField(
            model_name='sectionq',
            name='risk_perception_alcohol',
            field=models.CharField(blank=True, choices=[('none', 'Aucun'), ('slight', 'Petit'), ('moderate', 'Moyen'), ('great', 'Grand'), ('dont_know', 'Je sais pas')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionq',
            name='risk_perception_cannabis',
            field=models.CharField(blank=True, choices=[('none', 'Aucun'), ('slight', 'Petit'), ('moderate', 'Moyen'), ('great', 'Grand'), ('dont_know', 'Je sais pas')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionq',
            name='risk_perception_cigarettes',
            field=models.CharField(blank=True, choices=[('none', 'Aucun'), ('slight', 'Petit'), ('moderate', 'Moyen'), ('great', 'Grand'), ('dont_know', 'Je sais pas')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionq',
            name='risk_perception_nsp',
            field=models.CharField(blank=True, choices=[('none', 'Aucun'), ('slight', 'Petit'), ('moderate', 'Moyen'), ('great', 'Grand'), ('dont_know', 'Je sais pas')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionr',
            name='hours_school_day',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('30m', 'Une demi-heure ou moins'), ('1h', 'Environ 1 heure'), ('2_3h', 'Environ 2-3 heures'), ('4_5h', 'Environ 4-5 heures'), ('6h_plus', '6 heures ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionr',
            name='hours_weekend_day',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('30m', 'Une demi-heure ou moins'), ('1h', 'Environ 1 heure'), ('2_3h', 'Environ 2-3 heures'), ('4_5h', 'Environ 4-5 heures'), ('6h_plus', '6 heures ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sections',
            name='hours_school_day',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('30m', 'Une demi-heure ou moins'), ('1h', 'Environ 1 heure'), ('2_3h', 'Environ 2-3 heures'), ('4_5h', 'Environ 4-5 heures'), ('6h_plus', '6 heures ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sections',
            name='hours_weekend_day',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('30m', 'Une demi-heure ou moins'), ('1h', 'Environ 1 heure'), ('2_3h', 'Environ 2-3 heures'), ('4_5h', 'Environ 4-5 heures'), ('6h_plus', '6 heures ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectiont',
            name='felt_need_increase',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiont',
            name='lied_about_it',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectiont',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionu',
            name='theft_victim',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionv',
            name='restless',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('almost_never', 'Presque jamais'), ('sometimes', 'Parfois'), ('fairly_often', 'Assez souvent'), ('very_often', 'Très souvent')], max_length=20),
        ),
        migrations.AddField(
            model_name='sectionv',
            name='worthless',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('almost_never', 'Presque jamais'), ('sometimes', 'Parfois'), ('fairly_often', 'Assez souvent'), ('very_often', 'Très souvent')], max_length=20),
        ),
        migrations.AddField(
            model_name='sectionz',
            name='honesty_level',
            field=models.CharField(blank=True, choices=[('completely', 'Tout à fait'), ('mostly', 'En grande partie'), ('partially', 'Partiellement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionu',
            name='fights_12months',
            field=models.CharField(blank=True, choices=[('0', '0 fois'), ('1', '1 fois'), ('2', '2+ fois')], max_length=10),
        ),
    ]
