# Generated by Django 5.2.12 on 2026-03-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_school_staff_intervene_sectionu_bullied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionn',
            name='days_30_freq',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='age_first_use',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='days_30_freq',
        ),
        migrations.RemoveField(
            model_name='sectionq',
            name='risk_perception_alcohol',
        ),
        migrations.RemoveField(
            model_name='sectionq',
            name='risk_perception_cannabis',
        ),
        migrations.RemoveField(
            model_name='sectionq',
            name='risk_perception_cigarettes',
        ),
        migrations.RemoveField(
            model_name='sectionq',
            name='risk_perception_nsp',
        ),
        migrations.RemoveField(
            model_name='sectionr',
            name='days_per_week',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='days_per_week',
        ),
        migrations.RemoveField(
            model_name='sectiont',
            name='lifetime_freq',
        ),
        migrations.AddField(
            model_name='sectiona',
            name='parents_absence_reason_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='access_difficulty',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='cannabinoids_lifetime',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='cathinones_lifetime',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='forms_used_12months',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sectionq',
            name='help_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionq',
            name='risk_perceptions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionr',
            name='agreement_statements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sections',
            name='agreement_statements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sections',
            name='days_last_7_days',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sectiont',
            name='gambling_problems',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectiont',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectiont',
            name='offline_games',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectiont',
            name='online_games',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionu',
            name='fight_circumstances',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sectionu',
            name='fight_consequences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sectionu',
            name='fight_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sectionu',
            name='staff_intervention',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionz',
            name='honesty_cannabis',
            field=models.CharField(blank=True, choices=[('completely', 'Tout à fait'), ('mostly', 'En grande partie'), ('partially', 'Partiellement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionnairesession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schoolestablishment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectione',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionh',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectioni',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionj',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='age_first_use',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='lifetime_freq',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='months_12_freq',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sectionp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionr',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectiont',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionu',
            name='fights_12months',
            field=models.CharField(blank=True, choices=[('0', '0 fois'), ('1', '1 fois'), ('2_3', '2-3 fois'), ('4_5', '4-5 fois'), ('6_7', '6-7 fois'), ('8_9', '8-9 fois'), ('10_11', '10-11 fois'), ('12_plus', '12 fois ou plus')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionv',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
