# Generated by Django 5.2.12 on 2026-03-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sectionn_days_30_freq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionn',
            name='access_difficulty',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='cannabinoids_lifetime',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='cathinones_lifetime',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='forms_used_12months',
        ),
        migrations.RemoveField(
            model_name='sectionr',
            name='agreement_statements',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='agreement_statements',
        ),
        migrations.AddField(
            model_name='sectionn',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='forms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='synthetic_cannabinoids',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='synthetic_cathinones',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=20),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=15),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='substances',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionr',
            name='days_per_week',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sectionr',
            name='scale',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sections',
            name='scale',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('le9', '9 ans ou moins'), ('10', '10 ans'), ('11', '11 ans'), ('12', '12 ans'), ('13', '13 ans'), ('14', '14 ans'), ('15', '15 ans'), ('ge16', '16 ans ou plus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('1_2', '1-2 fois'), ('3_5', '3-5 fois'), ('6_9', '6-9 fois'), ('10_19', '10-19 fois'), ('20_39', '20-39 fois'), ('40_plus', '40 fois ou plus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionz',
            name='honesty_cannabis',
            field=models.CharField(blank=True, choices=[('already_admitted', "J'ai déjà admis"), ('definitely_yes', 'Certainement oui'), ('probably_yes', 'Probablement oui'), ('probably_no', 'Probablement non'), ('definitely_no', 'Certainement non')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionz',
            name='honesty_level',
            field=models.CharField(blank=True, choices=[('completely', 'Tout à fait'), ('mostly', 'En grande partie'), ('partially', 'Partiellement'), ('not_at_all', 'Pas du tout')], max_length=20),
        ),
    ]
