# Generated by Django 5.2.12 on 2026-03-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_sectionn_access_difficulty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionr',
            old_name='scale',
            new_name='agreement',
        ),
        migrations.RenameField(
            model_name='sectionr',
            old_name='hours_school_day',
            new_name='hours_per_day',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='scale',
            new_name='agreement',
        ),
        migrations.RenameField(
            model_name='sectionv',
            old_name='effort',
            new_name='confidence',
        ),
        migrations.RenameField(
            model_name='sectionv',
            old_name='depressed',
            new_name='control',
        ),
        migrations.RenameField(
            model_name='sectionv',
            old_name='hopeless',
            new_name='difficulties',
        ),
        migrations.RenameField(
            model_name='sectionv',
            old_name='nervous',
            new_name='success',
        ),
        migrations.RemoveField(
            model_name='sectionr',
            name='days_per_week',
        ),
        migrations.RemoveField(
            model_name='sectionr',
            name='hours_weekend_day',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='days_last_7_days',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='hours_school_day',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='hours_weekend_day',
        ),
        migrations.RemoveField(
            model_name='sectionv',
            name='restless',
        ),
        migrations.RemoveField(
            model_name='sectionv',
            name='worthless',
        ),
        migrations.AddField(
            model_name='sections',
            name='days_per_week',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sections',
            name='hours_per_day',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('30m', 'Une demi-heure ou moins'), ('1h', 'Environ 1 heure'), ('2_3h', 'Environ 2-3 heures'), ('4_5h', 'Environ 4-5 heures'), ('6h_plus', '6 heures ou plus')], max_length=15),
        ),
    ]
