# Generated by Django 6.0.2 on 2026-04-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_scale_sectionr_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesession',
            name='exclusion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairesession',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='fictive_substance_consumption',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10),
        ),
    ]
