# Generated by Django 6.0.4 on 2026-04-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_approval_status_user_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTerminology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value_fr', models.TextField()),
                ('value_ar', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
