# Generated by Django 6.0.4 on 2026-04-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_failed_attempts_user_last_login_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier (e.g., Z.01 or custom)', max_length=50, unique=True)),
                ('section', models.CharField(default='Z', help_text='Section letter where this question belongs', max_length=10)),
                ('label_fr', models.TextField()),
                ('label_ar', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('TEXT', 'Text Input'), ('RADIO', 'Single Choice'), ('NUMBER', 'Number Input')], default='TEXT', max_length=10)),
                ('options_json', models.JSONField(blank=True, default=list, help_text="List of choices for RADIO type: [['val', 'fr', 'ar'], ...]")),
                ('is_hidden', models.BooleanField(default=False, help_text='If True, this question (even core ones) will be hidden from the UI')),
                ('is_dynamic', models.BooleanField(default=True, help_text="True if added by admin, False if it's an override of a core question")),
                ('order', models.IntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.AddField(
            model_name='questionnairesession',
            name='extra_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Stores answers for dynamically added questions'),
        ),
    ]
