# Generated by Django 5.2.12 on 2026-04-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dynamicquestion_questionnairesession_extra_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicquestion',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text Input'), ('RADIO', 'Single Choice'), ('NUMBER', 'Number Input'), ('SECTION', 'New Section')], default='TEXT', max_length=10),
        ),
    ]
