# Generated by Django 5.2.12 on 2026-04-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_dynamicquestion_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=255)),
                ('establishment_type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Privé')], default='PUBLIC', max_length=10)),
                ('study_level', models.CharField(choices=[('1_AS', '1ère AS'), ('2_AS', '2ème AS')], max_length=10)),
                ('report_date', models.DateField()),
                ('students_present', models.IntegerField()),
                ('students_refused', models.IntegerField()),
                ('students_absent', models.IntegerField()),
                ('parental_authorization_required', models.BooleanField(default=False)),
                ('students_without_authorization', models.IntegerField(default=0)),
                ('questionnaires_collected', models.IntegerField()),
                ('perturbations', models.IntegerField(choices=[(1, 'Aucune'), (2, 'Quelques élèves'), (3, 'Plusieurs élèves')], default=1)),
                ('serious_work', models.IntegerField(choices=[(1, 'Tous'), (2, 'La majorité'), (3, 'Moitié ou moins')], default=1)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')], default=1)),
                ('planned_time_minutes', models.IntegerField()),
                ('first_student_time_minutes', models.IntegerField()),
                ('last_student_time_minutes', models.IntegerField()),
                ('personal_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reports', to='api.governorate')),
            ],
        ),
    ]
