# Generated by Django 5.2.12 on 2026-04-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_classreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='classreport',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_reports', to='api.schoolestablishment'),
        ),
        migrations.AddField(
            model_name='questionnairesession',
            name='class_report',
            field=models.ForeignKey(blank=True, help_text='Link to the administrative report for this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='api.classreport'),
        ),
    ]
