# Generated by Django 5.2.12 on 2026-04-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_classreport_establishment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairesession',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.governorate'),
        ),
        migrations.AlterField(
            model_name='questionnairesession',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.schoolestablishment'),
        ),
        migrations.AlterField(
            model_name='questionnairesession',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.schoolclass'),
        ),
    ]
