# Generated by Django 5.2.12 on 2026-04-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_questionnairesession_governorate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionc',
            name='family_smoke',
        ),
        migrations.RemoveField(
            model_name='sectionc',
            name='friends_smoke',
        ),
        migrations.RemoveField(
            model_name='sectiond',
            name='family_vape',
        ),
        migrations.RemoveField(
            model_name='sectiond',
            name='friends_vape',
        ),
        migrations.RemoveField(
            model_name='sectione',
            name='family_hookah',
        ),
        migrations.RemoveField(
            model_name='sectione',
            name='friends_hookah',
        ),
        migrations.RemoveField(
            model_name='sectiong',
            name='family_use',
        ),
        migrations.RemoveField(
            model_name='sectiong',
            name='friends_use',
        ),
        migrations.RemoveField(
            model_name='sectionh',
            name='family_use',
        ),
        migrations.RemoveField(
            model_name='sectionh',
            name='friends_use',
        ),
        migrations.RemoveField(
            model_name='sectioni',
            name='family_use',
        ),
        migrations.RemoveField(
            model_name='sectioni',
            name='friends_use',
        ),
        migrations.RemoveField(
            model_name='sectionj',
            name='family_use',
        ),
        migrations.RemoveField(
            model_name='sectionj',
            name='friends_use',
        ),
        migrations.RemoveField(
            model_name='sectionk',
            name='family_use',
        ),
        migrations.RemoveField(
            model_name='sectionk',
            name='friends_use',
        ),
        migrations.RemoveField(
            model_name='sectionl',
            name='family_use',
        ),
        migrations.RemoveField(
            model_name='sectionl',
            name='friends_use',
        ),
        migrations.RemoveField(
            model_name='sectionm',
            name='family_use',
        ),
        migrations.RemoveField(
            model_name='sectionm',
            name='friends_use',
        ),
        migrations.AddField(
            model_name='sectionc',
            name='social_circle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectiond',
            name='social_circle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectione',
            name='social_circle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectiong',
            name='social_circle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionh',
            name='social_circle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectioni',
            name='social_circle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionj',
            name='social_circle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionk',
            name='social_circle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionl',
            name='social_circle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionm',
            name='social_circle',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
