# Generated by Django 5.2.12 on 2026-04-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_sectionc_family_smoke_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioni',
            name='use_last_12months',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=5),
        ),
        migrations.AddField(
            model_name='sectionj',
            name='use_last_12months',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=5),
        ),
        migrations.AddField(
            model_name='sectionk',
            name='use_last_12months',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=5),
        ),
        migrations.AddField(
            model_name='sectionl',
            name='use_last_12months',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=5),
        ),
        migrations.AddField(
            model_name='sectionm',
            name='use_last_12months',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=5),
        ),
    ]
