# Generated by Django 5.2.12 on 2026-04-23 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_sectioni_use_last_12months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_reports_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
