# Generated by Django 5.2.12 on 2026-04-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_classreport_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='classreport',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
