# Generated by Django 5.2.12 on 2026-04-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_classreport_is_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiona',
            name='school_absences',
        ),
        migrations.RemoveField(
            model_name='sectionj',
            name='use_last_12months',
        ),
        migrations.RemoveField(
            model_name='sectionk',
            name='use_last_12months',
        ),
        migrations.RemoveField(
            model_name='sectionl',
            name='use_last_12months',
        ),
        migrations.RemoveField(
            model_name='sectionm',
            name='use_last_12months',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='substances',
        ),
        migrations.RemoveField(
            model_name='sectionq',
            name='friend_use_risk',
        ),
        migrations.RemoveField(
            model_name='sectionu',
            name='bullied',
        ),
        migrations.RemoveField(
            model_name='sectionu',
            name='theft_victim',
        ),
        migrations.RemoveField(
            model_name='sectionv',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='sectionv',
            name='control',
        ),
        migrations.RemoveField(
            model_name='sectionv',
            name='difficulties',
        ),
        migrations.RemoveField(
            model_name='sectionv',
            name='success',
        ),
        migrations.AddField(
            model_name='sectionp',
            name='age_crack',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='age_steroids',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AddField(
            model_name='sectionu',
            name='harassment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionv',
            name='stress_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='academic_performance',
            field=models.CharField(blank=True, choices=[('1', 'En dessous de la moyenne (<10/20)'), ('2', 'Moyen [10 – 12]'), ('3', 'En dessus de la moyenne (>12/20)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='nights_out_30days',
            field=models.CharField(blank=True, choices=[('1', 'Aucune'), ('2', '1'), ('3', '2'), ('4', '3'), ('5', '4'), ('6', '5'), ('7', '6'), ('8', '7 ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='parents_absence_reason',
            field=models.CharField(blank=True, choices=[('1', 'Décès'), ('2', 'Divorce/Séparation'), ('3', 'Migration'), ('4', 'Autre')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='economic_status',
            field=models.CharField(blank=True, choices=[('1', 'Supérieure aux autres familles'), ('2', 'Identique aux autres familles'), ('3', 'Inférieure aux autres familles'), ('4', 'Je ne sais pas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='father_education',
            field=models.CharField(blank=True, choices=[('1', 'Non scolarisé'), ('2', 'Primaire (n’a pas réussi sa 6ème année)'), ('3', 'Primaire (a réussi sa 6ème année)'), ('4', 'Collège (n’a pas réussi sa 9ème année)'), ('5', 'Collège (a réussi sa 9ème année)'), ('6', 'Secondaire (n’a pas réussi son BAC)'), ('7', 'Secondaire (a réussi son BAC)'), ('8', 'Supérieur ou plus'), ('9', 'Formation professionnelle'), ('10', 'Ne sait pas'), ('11', 'Non applicable')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='father_job',
            field=models.CharField(blank=True, choices=[('1', 'Oui, à plein temps'), ('2', 'Oui, à temps partiel'), ('3', 'Ne travaille pas'), ('4', 'Retraité(e)'), ('5', 'Je ne sais pas'), ('6', 'Non applicable')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='mother_education',
            field=models.CharField(blank=True, choices=[('1', 'Non scolarisé'), ('2', 'Primaire (n’a pas réussi sa 6ème année)'), ('3', 'Primaire (a réussi sa 6ème année)'), ('4', 'Collège (n’a pas réussi sa 9ème année)'), ('5', 'Collège (a réussi sa 9ème année)'), ('6', 'Secondaire (n’a pas réussi son BAC)'), ('7', 'Secondaire (a réussi son BAC)'), ('8', 'Supérieur ou plus'), ('9', 'Formation professionnelle'), ('10', 'Ne sait pas'), ('11', 'Non applicable')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='mother_job',
            field=models.CharField(blank=True, choices=[('1', 'Oui, à plein temps'), ('2', 'Oui, à temps partiel'), ('3', 'Ne travaille pas'), ('4', 'Retraité(e)'), ('5', 'Je ne sais pas'), ('6', 'Non applicable')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionc',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Impossible'), ('2', 'Difficile'), ('3', 'Facile'), ('4', 'Ne sait pas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionc',
            name='age_daily_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionc',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionc',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '< 1 cigarette par semaine'), ('3', '< 1 cigarette par jour'), ('4', '1-5 par jour'), ('5', '6-10 par jour'), ('6', '11-20 par jour'), ('7', '> 20 par jour')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionc',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionc',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Impossible'), ('2', 'Difficile'), ('3', 'Facile'), ('4', 'Ne sait pas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='age_daily_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '< 1 fois par semaine'), ('3', 'Au moins 1 fois par semaine'), ('4', 'Tous les jours ou presque')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectione',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Impossible'), ('2', 'Difficile'), ('3', 'Facile'), ('4', 'Ne sait pas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectione',
            name='age_daily_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectione',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectione',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '< 1 par semaine'), ('3', '< 1 par jour'), ('4', '1-5 par jour'), ('5', '6-10 par jour'), ('6', '11-20 par jour'), ('7', '> 20 par jour')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectione',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectione',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='age_first_drink',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='age_first_intoxication',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='binge_drinking_30days',
            field=models.CharField(blank=True, choices=[('1', 'Aucune fois'), ('2', '1'), ('3', '2'), ('4', '3-5'), ('5', '6-9'), ('6', '≥ 10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='intoxication_12months',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='intoxication_30days',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='intoxication_lifetime',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiong',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionh',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Impossible'), ('2', 'Difficile'), ('3', 'Facile'), ('4', 'Ne sait pas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionh',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionh',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionh',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionh',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectioni',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Impossible'), ('2', 'Difficile'), ('3', 'Facile'), ('4', 'Ne sait pas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectioni',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectioni',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectioni',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectioni',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectioni',
            name='use_last_12months',
            field=models.CharField(blank=True, choices=[('1', 'Oui'), ('2', 'Non')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionj',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Impossible'), ('2', 'Difficile'), ('3', 'Facile'), ('4', 'Ne sait pas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionj',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionj',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionj',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionj',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionk',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Impossible'), ('2', 'Difficile'), ('3', 'Facile'), ('4', 'Ne sait pas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionk',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionk',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionk',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionk',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionl',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Impossible'), ('2', 'Difficile'), ('3', 'Facile'), ('4', 'Ne sait pas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionl',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionl',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionl',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionl',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionm',
            name='access_difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Impossible'), ('2', 'Difficile'), ('3', 'Facile'), ('4', 'Ne sait pas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionm',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionm',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionm',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionm',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='synthetic_cannabinoids',
            field=models.CharField(blank=True, choices=[('1', 'Oui'), ('2', 'Non')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionn',
            name='synthetic_cathinones',
            field=models.CharField(blank=True, choices=[('1', 'Oui'), ('2', 'Non')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionp',
            name='age_first_use',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionp',
            name='days_30_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionp',
            name='fictive_substance_consumption',
            field=models.CharField(blank=True, choices=[('1', 'Oui'), ('2', 'Non')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionp',
            name='lifetime_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionp',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionr',
            name='hours_per_day',
            field=models.CharField(blank=True, choices=[('1', 'Aucune'), ('2', 'Une demi-heure ou moins'), ('3', 'Environ 1 heure'), ('4', 'Environ 2-3 heures'), ('5', 'Environ 4-5 heures'), ('6', '6 heures ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sections',
            name='days_per_week',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='sections',
            name='hours_per_day',
            field=models.CharField(blank=True, choices=[('1', 'Aucune'), ('2', 'Une demi-heure ou moins'), ('3', 'Environ 1 heure'), ('4', 'Environ 2-3 heures'), ('5', 'Environ 4-5 heures'), ('6', '6 heures ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiont',
            name='felt_need_increase',
            field=models.CharField(blank=True, choices=[('1', 'Oui'), ('2', 'Non')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiont',
            name='lied_about_it',
            field=models.CharField(blank=True, choices=[('1', 'Oui'), ('2', 'Non')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectiont',
            name='months_12_freq',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '1-2 fois'), ('3', '3-5 fois'), ('4', '6-9 fois'), ('5', '10-19 fois'), ('6', '20-39 fois'), ('7', '40 fois ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionu',
            name='fight_circumstances',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionu',
            name='fight_location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionu',
            name='fights_12months',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionu',
            name='serious_injury_12months',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionu',
            name='staff_intervention',
            field=models.CharField(blank=True, choices=[('1', 'Oui'), ('2', 'Non')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionz',
            name='honesty_cannabis',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionz',
            name='honesty_level',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
