# Generated by Django 5.2.12 on 2026-04-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_sectiona_school_absences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiona',
            name='school_appreciation',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='private_room',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='sectionz',
            name='honesty_heroin',
            field=models.CharField(blank=True, choices=[('1', 'Jamais'), ('2', '9 ans ou moins'), ('3', '10 ans'), ('4', '11 ans'), ('5', '12 ans'), ('6', '13 ans'), ('7', '14 ans'), ('8', '15 ans'), ('9', '16 ans ou plus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='economic_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
