# Generated by Django 5.2.12 on 2026-04-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_sectiona_school_appreciation_sectionb_private_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionn',
            name='age_first_use',
        ),
        migrations.RemoveField(
            model_name='sectionn',
            name='days_30_freq',
        ),
        migrations.RemoveField(
            model_name='sectionn',
            name='lifetime_freq',
        ),
        migrations.RemoveField(
            model_name='sectionn',
            name='months_12_freq',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='age_crack',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='age_steroids',
        ),
        migrations.RemoveField(
            model_name='sectionr',
            name='hours_per_day',
        ),
        migrations.AddField(
            model_name='sectiona',
            name='school_absences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionj',
            name='use_last_12months',
            field=models.CharField(blank=True, choices=[('1', 'Oui'), ('2', 'Non')], max_length=2),
        ),
        migrations.AddField(
            model_name='sectionk',
            name='use_last_12months',
            field=models.CharField(blank=True, choices=[('1', 'Oui'), ('2', 'Non')], max_length=2),
        ),
        migrations.AddField(
            model_name='sectionl',
            name='use_last_12months',
            field=models.CharField(blank=True, choices=[('1', 'Oui'), ('2', 'Non')], max_length=2),
        ),
        migrations.AddField(
            model_name='sectionm',
            name='use_last_12months',
            field=models.CharField(blank=True, choices=[('1', 'Oui'), ('2', 'Non')], max_length=2),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='access_difficulty',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='age_first_use_by_type',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='days_30_freq_by_type',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='lifetime_freq_by_type',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionn',
            name='months_12_freq_by_type',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='forms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionp',
            name='substances',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionr',
            name='hours_per_day_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionv',
            name='a',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='sectionv',
            name='b',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='sectionv',
            name='c',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='sectionv',
            name='d',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
