# Generated by Django 5.2.12 on 2026-04-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_sectionn_age_first_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionn',
            name='days_30_freq_by_type',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='age_first_use',
        ),
        migrations.RemoveField(
            model_name='sectionp',
            name='days_30_freq',
        ),
        migrations.AddField(
            model_name='sectionv',
            name='help_seeking',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionv',
            name='mental_health_states',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sectionv',
            name='self_esteem',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
