# Generated by Django 5.2.12 on 2026-04-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_sectionn_days_30_freq_by_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classreport',
            name='first_student_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classreport',
            name='last_student_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classreport',
            name='planned_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classreport',
            name='questionnaires_collected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classreport',
            name='students_absent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='classreport',
            name='students_present',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classreport',
            name='students_refused',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
