# Generated by Django 5.2.14 on 2026-07-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_classreport_first_student_time_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('GLOBAL_ADMIN', 'Global Admin'), ('OPERATOR', 'Operator'), ('REGIONAL_ADMIN', 'Regional Admin'), ('PRACTITIONER', 'Practitioner')], default='PRACTITIONER', max_length=20),
        ),
    ]
