# Generated by Django 5.2.14 on 2026-08-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_invitetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='classreport',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores dynamic custom fields added to class reports'),
        ),
    ]
