# Generated by Django 5.2.14 on 2026-08-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_classreport_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicClassReportField',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('section', models.CharField(default='identity', max_length=50)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('field_type', models.CharField(choices=[('TEXT', 'Texte'), ('NUMBER', 'Nombre'), ('SELECT', 'Liste déroulante'), ('RADIO', 'Boutons radio'), ('CHECKBOX', 'Case à cocher'), ('TEXTAREA', 'Zone de texte')], default='TEXT', max_length=20)),
                ('options_json', models.JSONField(blank=True, default=list, help_text="[['val', 'label_fr', 'label_ar'], ...]")),
                ('order', models.IntegerField(default=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
